# Sets Travis to run the Ruby specs on OS X machines which are required to
# use the native tools to read plists.
#
language: objective-c

env:
  - RVM_RUBY_VERSION=system

before_install:
  - source ~/.rvm/scripts/rvm
  - if [[ $RVM_RUBY_VERSION != 'system' ]]; then rvm install $RVM_RUBY_VERSION; fi
  - rvm use $RVM_RUBY_VERSION
  - if [[ $RVM_RUBY_VERSION == 'system' ]]; then sudo gem install bundler --no-ri --no-rdoc; else gem install bundler --no-ri --no-rdoc; fi

install:
  - bundle install --without=documentation

script: rake spec
